site_name: pythaidate
site_description: Thai Calendar Systems for Python
site_author: Mark Hollow
repo_url: https://github.com/hmmbug/pythaidate
theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - toc.integrate

nav:
  - Home: index.md
  - User Guide:
    - Chulasakarat Calendar: user-guide/csdate.md
    - Pakkhakhananaa Calendar: user-guide/pakdate.md
  - API Reference:
    - CsDate: api/csdate.md
    - PakDate: api/pakdate.md
    - Helpers: api/helpers.md
  - About:
    - References: about/references.md
    - License: about/license.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - footnotes

plugins:
  - search 